[workspace]

resolver = "2" # this is required for the wgpu frontend

members = [
    "image-to-text",
    "audio-data",
    "procgen",
    "game",
    "app",
    "native",
    "ansi-terminal",
    "web",
    "ggez",
    "sdl2",
    "wgpu",
    "util/vector",
    "util/rand-range",
    "util/rational",
]

[profile.release]
lto = true
